language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
gemfile:
  - ci/Gemfile-rails-4-2
  - ci/Gemfile-rails-5-0
  - ci/Gemfile-rails-5-1
  - ci/Gemfile-rails-5-2
  - ci/Gemfile-rails-6-0
matrix:
  exclude:
    - rvm: 2.7.1
      gemfile: ci/Gemfile-rails-4-2
script:
  - bundle exec rake
before_install:
  - gem update bundler
sudo: false
